### ISSUE TITLE
bash: bamtools: command not found

### ISSUE THREAD

**Issue by annarerra** [bhattlab/StrainSifter#1]
Hello,

When I run the command _snakemake {prefix}.tree.pdf_ i have an error **bash: bamtools: command not found**
and a bit later this:

**Error in rule bwa_align:
    jobid: 36
    output: filtered_bam/sample2.filtered.bam
    shell:
        bwa mem -t 1 /site/ly/work/projects/Share/ESPRIOAC_FUI/WGSre/127_patient1_clones_metasamples_freqvar/DB/patient1_plvt_19004237701_clB1_21_ref.20201007.fasta /site/ly/work/projects/Share/ESPRIOAC_FUI/WGSre/127_patient1_clones_metasamples_freqvar/Raw/patient1_plvt_19004237701_clB1_23_S25_R1_001.fastq.gz /site/ly/work/projects/Share/ESPRIOAC_FUI/WGSre/127_patient1_clones_metasamples_freqvar/Raw/patient1_plvt_19004237701_clB1_23_S25_R2_001.fastq.gz | samtools view -b -q 60 | bamtools filter -tag 'NM:<=5' | samtools sort --threads 1 -o filtered_bam/sample2.filtered.bam
        (exited with non-zero exit code)**

Do you have an idea what can be the problem?
(bamtools & samtools (1.11) are already installed in the environment)

environment.yaml:
name: ssift
channels:
  - conda-forge
  - r
  - bioconda
  - defaults
dependencies:
  - bwa
  - samtools
  - ncurses
  - bamtools
  - bedtools
  - MUSCLE
  - FastTree
  - r-ggplot2
  - bioconductor-ggtree
  - r-phangorn
  - snakemake=5.6.0

Thank you in advance :)

**Comment by bsiranosian** [comment]
Hi, what happens if you call `bamtools` from your shell, outside of snakemake? 

On another note, this workflow hasn't been updated since 2018 when the author graduated. You might try Snippy (https://github.com/tseemann/snippy) for a more updated workflow that has very similar functionality. 

Cheers

**Comment by annarerra** [comment]
Hello bsiranosian,

Thank you for your reply.

When i do bamtools outside of snakemake :
**bash: bamtools: command not found...**

and when inside:
**usage: bamtools [--help] COMMAND [ARGS]**

Best

**Comment by bsiranosian** [comment]
So it looks like some bamtools installation error. Unfortunately I cannot help you troubleshoot this further.

**Comment by annarerra** [comment]
It is ok, thank you anyway :)
I will find a way, or I will use the snippy as you proposed!
